<script lang="ts">
	import {
		Badge,
		Button,
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle,
		Input,
		Separator,
		Tabs,
		TabsContent,
		TabsList,
		TabsTrigger
	} from '$lib/components/ui';
	import { base64DevinIcon } from '$lib/deepwiki';
	import { checkIfRepositoryExists } from '$lib/github';
	import { Github, Loader } from 'lucide-svelte';
	import CopyIcon, { copyToClipboard } from './copy.svelte';
	
	let owner = $state('');
	let repo = $state('');
	let urlError = $state<string | null>(null);
	let isLoading = $state(false);
	let repositoryCheckResult = $state<Awaited<ReturnType<typeof checkIfRepositoryExists>> | null>(null);
	
	const convertText = (text: string) => {
		return text.replace(/_/g, "__").replace(/-/g, "--");
	};
	
	const badgeUrl = $derived(
		`https://img.shields.io/badge/DeepWiki-${convertText(owner || "owner")}%2F${convertText(repo || "repo")}-blue.svg?logo=${base64DevinIcon()}`
	);
	const deepWikiUrl = $derived(`https://deepwiki.com/${owner}/${repo}`);
	const markdownCode = $derived(`[![DeepWiki](${badgeUrl})](${deepWikiUrl})`);
	const htmlCode = $derived(`<a href="${deepWikiUrl}"><img src="${badgeUrl}" alt="DeepWiki"></a>`);
	const creditComment = "<!-- DeepWiki badge generated by https://deepwiki.ryoppippi.com/ -->";
	
	function parseGitHubUrl(url: string) {
		try {
			urlError = null;
			
			if (!url.trim()) {
				owner = '';
				repo = '';
				return;
			}
			
			if (url.includes("github.com")) {
				const githubRegex = /github\.com\/([^/]+)\/([^/]+)/;
				const match = url.match(githubRegex);
				
				if (match && match.length >= 3) {
					const extractedOwner = match[1];
					const extractedRepo = match[2].split("/")[0];
					
					owner = extractedOwner;
					repo = extractedRepo;
				} else {
					urlError = "Invalid GitHub repository URL format";
					owner = '';
					repo = '';
				}
			} else {
				const simpleRegex = /^([^/]+)\/([^/]+)$/;
				const simpleMatch = url.trim().match(simpleRegex);
				
				if (simpleMatch && simpleMatch.length >= 3) {
					owner = simpleMatch[1];
					repo = simpleMatch[2];
				} else {
					urlError = "Please enter a valid GitHub URL (e.g., https://github.com/owner/repo)";
					owner = '';
					repo = '';
				}
			}
		} catch (error) {
			console.error("Error parsing GitHub URL:", error);
			urlError = "Error parsing URL";
		}
	}
	
	async function generateBadge() {
		if (!owner || !repo) return;
		
		isLoading = true;
		repositoryCheckResult = null;
		
		try {
			repositoryCheckResult = await checkIfRepositoryExists({ owner, repo });
		} finally {
			isLoading = false;
		}
	}
	
	let tabValue = $state('markdown');
</script>

<Card class="w-full">
	<CardHeader>
		<CardTitle>Generate Your Badge</CardTitle>
		<CardDescription>
			Generate badges from your GitHub repositories
		</CardDescription>
	</CardHeader>
	<CardContent class="space-y-6">
		<div class="space-y-2">
			<label for="repoUrl" class="text-sm font-medium">
				GitHub Repository URL
			</label>
			<div class="flex items-center space-x-2">
				<Github class="size-4 text-muted-foreground" />
				<Input
					id="repoUrl"
					placeholder="https://github.com/owner/repo"
					oninput={(e) => parseGitHubUrl(e.currentTarget.value)}
					class={urlError ? "border-red-500 focus-visible:ring-red-500" : ""}
				/>
			</div>
			{#if urlError}
				<p class="text-sm text-red-500 mt-1">{urlError}</p>
			{/if}
		</div>
		
		{#if owner && repo}
			<div class="mt-2 flex items-center space-x-2">
				<span class="text-sm text-muted-foreground">Detected:</span>
				<Badge variant="outline" class="font-mono">
					{owner}/{repo}
				</Badge>
			</div>
		{/if}
		
		<Button
			onclick={generateBadge}
			disabled={(!owner && !repo) || isLoading}
			class="w-full"
		>
			{#if isLoading}
				<Loader class="mr-2 size-4 animate-spin" />
				Checking Repository
			{:else}
				Generate Badge from URL
			{/if}
		</Button>
		
		{#if repositoryCheckResult}
			{#if repositoryCheckResult.isErr()}
				<div class="text-center p-4 border rounded-md bg-muted">
					<p class="text-destructive font-medium">
						Repository not found or private
					</p>
					<p class="text-sm text-muted-foreground mt-1">
						Make sure the repository is public and exists on DeepWiki.
					</p>
				</div>
			{:else}
				<div class="space-y-4">
					<div class="flex items-center justify-center py-4">
						<Badge variant="outline" class="text-base py-1 px-3">
							<a href={deepWikiUrl} target="_blank" rel="noopener noreferrer">
								<img src={badgeUrl} alt="DeepWiki Badge" />
							</a>
						</Badge>
					</div>
					
					<Separator />
					
					<div class="space-y-2">
						<h3 class="text-sm font-medium">Embed this badge in your README</h3>
						
						<Tabs bind:value={tabValue} class="w-full">
							<TabsList class="grid w-full grid-cols-2">
								<TabsTrigger value="markdown">Markdown</TabsTrigger>
								<TabsTrigger value="html">HTML</TabsTrigger>
							</TabsList>
							<TabsContent value="markdown" class="space-y-2">
								<div class="relative">
									<pre class="bg-muted p-4 rounded-md overflow-x-auto text-sm">
										<code>{markdownCode}</code>
									</pre>
									<Button
										size="sm"
										variant="ghost"
										class="absolute top-2 right-2"
										onclick={() => copyToClipboard(`${markdownCode}\n${creditComment}`, 'markdown')}
									>
										<CopyIcon type="markdown" />
									</Button>
								</div>
							</TabsContent>
							<TabsContent value="html" class="space-y-2">
								<div class="relative">
									<pre class="bg-muted p-4 rounded-md overflow-x-auto text-sm">
										<code>{htmlCode}</code>
									</pre>
									<Button
										size="sm"
										variant="ghost"
										class="absolute top-2 right-2"
										onclick={() => copyToClipboard(`${htmlCode}\n${creditComment}`, 'html')}
									>
										<CopyIcon type="html" />
									</Button>
								</div>
							</TabsContent>
						</Tabs>
					</div>
				</div>
			{/if}
		{/if}
	</CardContent>
</Card>