<script lang='ts'>
	import {
		Button,
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle,
		Separator,
	} from '$lib/components/ui';
	import { base64DevinIcon } from '$lib/deepwiki';
	import { checkIfRepositoryExists } from '$lib/github';
	import Loader from '~icons/lucide/loader';
	import BadgeCodeTabs from './badge-code-tabs.svelte';
	import BadgePreview from './badge-preview.svelte';
	import RepositoryInput from './repository-input.svelte';
	import RepositoryStatus from './repository-status.svelte';

	let owner = $state('');
	let repo = $state('');
	let urlError = $state<string | null>(null);
	let isLoading = $state(false);
	let repositoryCheckResult = $state<Awaited<ReturnType<typeof checkIfRepositoryExists>> | null>(null);

	const convertText = (text: string) => {
		return text.replace(/_/g, '__').replace(/-/g, '--');
	};

	const badgeUrl = $derived(
		`https://img.shields.io/badge/DeepWiki-${convertText(owner || 'owner')}%2F${convertText(repo || 'repo')}-blue.svg?logo=${base64DevinIcon()}`,
	);
	const deepWikiUrl = $derived(`https://deepwiki.com/${owner}/${repo}`);
	const markdownCode = $derived(`[![DeepWiki](${badgeUrl})](${deepWikiUrl})`);
	const htmlCode = $derived(`<a href="${deepWikiUrl}"><img src="${badgeUrl}" alt="DeepWiki"></a>`);
	const creditComment = '<!-- DeepWiki badge generated by https://deepwiki.ryoppippi.com/ -->';

	function parseGitHubUrl(url: string) {
		try {
			urlError = null;

			if (!url.trim()) {
				owner = '';
				repo = '';
				return;
			}

			if (url.includes('github.com')) {
				const githubRegex = /github\.com\/([^/]+)\/([^/]+)/;
				const match = url.match(githubRegex);

				if (match && match.length >= 3) {
					const extractedOwner = match[1];
					const extractedRepo = match[2].split('/')[0];

					owner = extractedOwner;
					repo = extractedRepo;
				}
				else {
					urlError = 'Invalid GitHub repository URL format';
					owner = '';
					repo = '';
				}
			}
			else {
				const simpleRegex = /^([^/]+)\/([^/]+)$/;
				const simpleMatch = url.trim().match(simpleRegex);

				if (simpleMatch && simpleMatch.length >= 3) {
					owner = simpleMatch[1];
					repo = simpleMatch[2];
				}
				else {
					urlError = 'Please enter a valid GitHub URL (e.g., https://github.com/owner/repo)';
					owner = '';
					repo = '';
				}
			}
		}
		catch (error) {
			console.error('Error parsing GitHub URL:', error);
			urlError = 'Error parsing URL';
		}
	}

	async function generateBadge() {
		if (!owner || !repo) {
			return;
		}

		isLoading = true;
		repositoryCheckResult = null;

		try {
			repositoryCheckResult = await checkIfRepositoryExists({ owner, repo });
		}
		finally {
			isLoading = false;
		}
	}
</script>

<Card class='w-full'>
	<CardHeader>
		<CardTitle>Generate Your Badge</CardTitle>
		<CardDescription>
			Generate badges from your GitHub repositories
		</CardDescription>
	</CardHeader>
	<CardContent class='space-y-6'>
		<RepositoryInput
			onUrlChange={parseGitHubUrl}
			{owner}
			{repo}
			{urlError}
		/>

		<Button
			class='w-full'
			disabled={(!owner && !repo) || isLoading}
			onclick={generateBadge}
		>
			{#if isLoading}
				<Loader class='mr-2 size-4 animate-spin' />
				Checking Repository
			{:else}
				Generate Badge from URL
			{/if}
		</Button>

		{#if repositoryCheckResult}
			<RepositoryStatus {repositoryCheckResult}>
				<div class='space-y-4'>
					<BadgePreview {badgeUrl} {deepWikiUrl} />
					<Separator />
					<BadgeCodeTabs {creditComment} {htmlCode} {markdownCode} />
				</div>
			</RepositoryStatus>
		{/if}
	</CardContent>
</Card>
